### PR TITLE
Add chronograf for influxdb webadmin/UI

### PR DESCRIPTION
**Pull request by krisgeus**

### CODE REVIEW

**Comment by samuelebistoletti** [comment]
Thank you for the contribution!

**Comment by krisgeus** [comment]
@samuelebistoletti I see the circle-ci is green again. Does the image in docker hub get build automatically or do you need to do a manual build for that?

Would be great to use your image as base instead of my own local one

**Comment by samuelebistoletti** [comment]
Image will be automatically build if all tests pass. So in that case you will find updated image in the next 30 minutes. I see that it is in queue for build process.

**Comment by krisgeus** [comment]
@samuelebistoletti There is a newer 2.0.0 image but it doesn't have the chronograf installation. It does have the new supervisor config though. The dockerfile in dockerhub is still the old one.
Any ideas on how this can be?
Although i'm not sure about the supervisor config because that is coming from my override.

**Comment by samuelebistoletti** [comment]
Maybe you have to use the tag "latest"

**Comment by krisgeus** [comment]
docker run -d \
  --name docker-statsd-influxdb-grafana \
  -p 3003:3003 \
  -p 3004:8888 \
  -p 8086:8086 \
  -p 22022:22 \
  -p 8125:8125/udp \
  samuelebistoletti/docker-statsd-influxdb-grafana:latest


docker ps

```
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS              PORTS                                                                                                                   NAMES
72bfa481b1e5        samuelebistoletti/docker-statsd-influxdb-grafana:latest   "/usr/bin/supervisord"   4 seconds ago       Up 5 seconds        0.0.0.0:3003->3003/tcp, 0.0.0.0:8086->8086/tcp, 0.0.0.0:8125->8125/udp, 0.0.0.0:22022->22/tcp, 0.0.0.0:3004->8888/tcp   docker-statsd-influxdb-grafana2
```

docker exec -ti 72bfa481b1e5 /bin/bash

```
root@72bfa481b1e5:~# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /usr/bin/python /usr/bin/supervisord
   10 ?        S      0:00 /usr/sbin/sshd -D
   11 ?        S      0:00 bash -c /etc/init.d/mysql start && sleep 5
   15 ?        S      0:00 /bin/bash /etc/init.d/mysql start
   50 ?        Sl     0:00 /usr/bin/telegraf -pidfile /var/run/telegraf/telegraf
   68 ?        Sl     0:00 /usr/bin/influxd -pidfile /var/run/influxdb/influxd.p
  675 ?        S      0:00 bash /etc/init.d/grafana-server start
  761 pts/0    Ss     0:00 /bin/bash
  801 ?        S      0:00 sleep 1
  805 ?        S      0:00 sleep 1
  806 pts/0    R+     0:00 ps ax
```
root@72bfa481b1e5:~# cat /etc/supervisor/conf.d/supervisord.conf 

```
[supervisord]
nodaemon = true

[program:sshd]
priority = 1
command = /usr/sbin/sshd -D

[program:mysql]
priority = 2
command = bash -c "/etc/init.d/mysql start && sleep 5"

[program:influxdb]
priority = 3
command = bash -c "/etc/init.d/influxdb start && sleep 5"

[program:telegraf]
priority = 4
command = /etc/init.d/telegraf start

[program:grafana]
priority = 5
command = /etc/init.d/grafana-server start
root@72bfa481b1e5:~# 
```

**Comment by krisgeus** [comment]
Still old stuff here. Looks like Dockerhub might be pointing to old tag or release??

**Comment by krisgeus** [comment]
Docker hub indeed checks out this 'old' commit: https://github.com/samuelebistoletti/docker-statsd-influxdb-grafana/commit/362ae39868133657787da49c6815e3a951b12b90
Seems to be the 2.0.0 tag

**Comment by samuelebistoletti** [comment]
My bad, sorry. I did not remember that Docker Hub was pointed to the old repo tag. Now it should be fixed and it's building the image, should check it out in 30 minutes.

**Pull request merged**
