### PR TITLE
Update grafana, update readme, change telegraf interval.

### PR DESCRIPTION
**Pull request by lisbakke**

### CODE REVIEW

**Comment by krisgeus** [comment]
Any reason this is not merged yet? LGTM.

**Comment by samuelebistoletti** [comment]
Sorry, forgot about that. Merged right now.

**Comment by krisgeus** [comment]
Thx. Is it possible to also update the docker image on docker hub?

**Comment by krisgeus** [comment]
Ah I see the build failed here: https://circleci.com/gh/samuelebistoletti/docker-statsd-influxdb-grafana/19

Reason for that is that the build checks for port 3004 but the upgrade of influxdb made it so that this influx UI is not available anymore.

@samuelebistoletti @lisbakke I believe the current way to query influx is using chronograf (https://docs.influxdata.com/influxdb/v1.4/tools/web_admin/)

**Comment by krisgeus** [comment]
https://github.com/samuelebistoletti/docker-statsd-influxdb-grafana/pull/25

**Pull request merged**
